### ISSUE TITLE
L'image d'illustration n'est pas affichée lors de la lecture de l'article

### ISSUE THREAD

**Issue by mariuslp** [sghribi/garopi#1]
Alors que c'est un incontournable.

Cdt,

**Comment by sghribi** [comment]
Le ticket correspondant n'a simplement pas encore été traité.

Bien cordialement,

**Comment by mariuslp** [comment]
Bonjour,

Merci de cette réponse. Pourrions-nous avoir accès aux tickets du board de développement ? Si ce projet est open-source, cela me semble être une bonne pratique. 

Cordialement,

**Comment by sghribi** [comment]
Bonsoir M. Serendip,

Le ticket vient d'être finalisé et déployé en prod. Pour cette intervention, un forfait SLA 10h vous sera facturé, merci de régler votre situation au plus vite.

Pour ce qui est de l'accès au board de développement, celui-ci doit rester privé, pour des raisons de confidentialités évidentes.

Je vous remercie de l'attention que vous nous portez.

Très cordialement,
